float32[3] position	# north, east, hieght (m)
float32 Vw		# wheelspeed (m/s)
float32 phi		# Roll angle (rad)
float32 theta		# Pitch angle (rad)
float32 psi		# Yaw angle (rad)
float32 chi		# Course angle (rad)
float32 p		# Body frame rollrate (rad/s)
float32 q		# Body frame pitchrate (rad/s)
float32 r		# Body frame yawrate (rad/s)
float32 Vg		# Groundspeed (m/s)
float64 base_latitude   # Latitude [degrees]. Positive is north of equator; negative is south.
float64 base_longitude  # Longitude [degrees]. Positive is east of prime meridian; negative is west.
float64 base_altitude   # Altitude [m]. Positive is above the WGS 84 ellipsoid
