// Generated by gencpp from file rover_msgs/Arm.msg
// DO NOT EDIT!


#ifndef ROVER_MSGS_MESSAGE_ARM_H
#define ROVER_MSGS_MESSAGE_ARM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_msgs
{
template <class ContainerAllocator>
struct Arm_
{
  typedef Arm_<ContainerAllocator> Type;

  Arm_()
    : tur(0)
    , sh(0)  {
    }
  Arm_(const ContainerAllocator& _alloc)
    : tur(0)
    , sh(0)  {
    }



   typedef uint16_t _tur_type;
  _tur_type tur;

   typedef uint16_t _sh_type;
  _sh_type sh;




  typedef boost::shared_ptr< ::rover_msgs::Arm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_msgs::Arm_<ContainerAllocator> const> ConstPtr;

}; // struct Arm_

typedef ::rover_msgs::Arm_<std::allocator<void> > Arm;

typedef boost::shared_ptr< ::rover_msgs::Arm > ArmPtr;
typedef boost::shared_ptr< ::rover_msgs::Arm const> ArmConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_msgs::Arm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_msgs::Arm_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rover_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rover_msgs': ['/home/kyle/gitMars/ros_nav_gui_ws/src/rover_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::Arm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::Arm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::Arm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::Arm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::Arm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::Arm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_msgs::Arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a106f4b259cd6c1addd28eb4eb5100f";
  }

  static const char* value(const ::rover_msgs::Arm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a106f4b259cd6c1ULL;
  static const uint64_t static_value2 = 0xaddd28eb4eb5100fULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_msgs::Arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_msgs/Arm";
  }

  static const char* value(const ::rover_msgs::Arm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_msgs::Arm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 tur\n\
uint16 sh\n\
";
  }

  static const char* value(const ::rover_msgs::Arm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_msgs::Arm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tur);
      stream.next(m.sh);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Arm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_msgs::Arm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_msgs::Arm_<ContainerAllocator>& v)
  {
    s << indent << "tur: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.tur);
    s << indent << "sh: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.sh);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MSGS_MESSAGE_ARM_H
