// Generated by gencpp from file rover_msgs/Chutes.msg
// DO NOT EDIT!


#ifndef ROVER_MSGS_MESSAGE_CHUTES_H
#define ROVER_MSGS_MESSAGE_CHUTES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_msgs
{
template <class ContainerAllocator>
struct Chutes_
{
  typedef Chutes_<ContainerAllocator> Type;

  Chutes_()
    : chutes(0)  {
    }
  Chutes_(const ContainerAllocator& _alloc)
    : chutes(0)  {
    }



   typedef uint16_t _chutes_type;
  _chutes_type chutes;




  typedef boost::shared_ptr< ::rover_msgs::Chutes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_msgs::Chutes_<ContainerAllocator> const> ConstPtr;

}; // struct Chutes_

typedef ::rover_msgs::Chutes_<std::allocator<void> > Chutes;

typedef boost::shared_ptr< ::rover_msgs::Chutes > ChutesPtr;
typedef boost::shared_ptr< ::rover_msgs::Chutes const> ChutesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_msgs::Chutes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_msgs::Chutes_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rover_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rover_msgs': ['/home/kyle/gitMars/ros_nav_gui_ws/src/rover_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::Chutes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::Chutes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::Chutes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::Chutes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::Chutes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::Chutes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_msgs::Chutes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "735dabca75806217d50ebaff1a183d1b";
  }

  static const char* value(const ::rover_msgs::Chutes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x735dabca75806217ULL;
  static const uint64_t static_value2 = 0xd50ebaff1a183d1bULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_msgs::Chutes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_msgs/Chutes";
  }

  static const char* value(const ::rover_msgs::Chutes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_msgs::Chutes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 chutes\n\
";
  }

  static const char* value(const ::rover_msgs::Chutes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_msgs::Chutes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.chutes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Chutes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_msgs::Chutes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_msgs::Chutes_<ContainerAllocator>& v)
  {
    s << indent << "chutes: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.chutes);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MSGS_MESSAGE_CHUTES_H
