// Generated by gencpp from file rover_msgs/Drive.msg
// DO NOT EDIT!


#ifndef ROVER_MSGS_MESSAGE_DRIVE_H
#define ROVER_MSGS_MESSAGE_DRIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_msgs
{
template <class ContainerAllocator>
struct Drive_
{
  typedef Drive_<ContainerAllocator> Type;

  Drive_()
    : lw(0)
    , rw(0)
    , pan(0)
    , tilt(0)
    , camnum(0)  {
    }
  Drive_(const ContainerAllocator& _alloc)
    : lw(0)
    , rw(0)
    , pan(0)
    , tilt(0)
    , camnum(0)  {
    }



   typedef uint16_t _lw_type;
  _lw_type lw;

   typedef uint16_t _rw_type;
  _rw_type rw;

   typedef uint16_t _pan_type;
  _pan_type pan;

   typedef uint16_t _tilt_type;
  _tilt_type tilt;

   typedef uint8_t _camnum_type;
  _camnum_type camnum;




  typedef boost::shared_ptr< ::rover_msgs::Drive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_msgs::Drive_<ContainerAllocator> const> ConstPtr;

}; // struct Drive_

typedef ::rover_msgs::Drive_<std::allocator<void> > Drive;

typedef boost::shared_ptr< ::rover_msgs::Drive > DrivePtr;
typedef boost::shared_ptr< ::rover_msgs::Drive const> DriveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_msgs::Drive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_msgs::Drive_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rover_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rover_msgs': ['/home/kyle/gitMars/ros_nav_gui_ws/src/rover_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::Drive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::Drive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::Drive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::Drive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::Drive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::Drive_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_msgs::Drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6dbf1ff82d4e5af7bd6088c316a10468";
  }

  static const char* value(const ::rover_msgs::Drive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6dbf1ff82d4e5af7ULL;
  static const uint64_t static_value2 = 0xbd6088c316a10468ULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_msgs::Drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_msgs/Drive";
  }

  static const char* value(const ::rover_msgs::Drive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_msgs::Drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 lw\n\
uint16 rw\n\
uint16 pan\n\
uint16 tilt\n\
uint8 camnum\n\
";
  }

  static const char* value(const ::rover_msgs::Drive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_msgs::Drive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lw);
      stream.next(m.rw);
      stream.next(m.pan);
      stream.next(m.tilt);
      stream.next(m.camnum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Drive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_msgs::Drive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_msgs::Drive_<ContainerAllocator>& v)
  {
    s << indent << "lw: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.lw);
    s << indent << "rw: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.rw);
    s << indent << "pan: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.pan);
    s << indent << "tilt: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.tilt);
    s << indent << "camnum: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.camnum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MSGS_MESSAGE_DRIVE_H
