(cl:in-package rover_msgs-msg)
(cl:export '(LW-VAL
          LW
          RW-VAL
          RW
          PAN-VAL
          PAN
          TILT-VAL
          TILT
          CAMNUM-VAL
          CAMNUM
          Q1-VAL
          Q1
          Q2-VAL
          Q2
          Q3-VAL
          Q3
          Q4-VAL
          Q4
          Q5-VAL
          Q5
          Q6-VAL
          Q6
          GRIP-VAL
          GRIP
          CHUTES-VAL
          CHUTES
          SHOVEL-VAL
          SHOVEL
))